- name: Configure Openvpn Server
  hosts: openvpn_server
  become: yes

  vars:
   ca_dir: "/etc/easy-rsa"
   client_dir: "/etc/openvpn/client"
   vpn_user: "devops"

  roles:
    - role: openvpn
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

